--- 
title: "Travaux Pratiques de Biométrie 2"
author: "Benoît Simon-Bouhet"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    highlight: kate
    config:
      edit: null
      download: no
      sharing:
        twitter: no
        facebook: no
        github: yes
        all: no
url: 'https\://besibo.github.io/Biometrie2/'
github-repo: "besibo/Biometrie2"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Ce livre est un document permettant de prendre en main les logiciels R et RStudio afin de réaliser des représentations graphiques et des statistiques descriptives simples dans le cadre des travaux pratiques de Biométrie 2."
---

# Préambule

Ce livre contient l'ensemble du matériel (contenus, exemples, exercices...) nécessaire à la réalisation des travaux pratiques de biométrie 2.


```{r package_bibliography, include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'tidyverse'
), 'packages.bib')
```


```{r setup, include=FALSE, cache=FALSE, results=FALSE, message=FALSE}
options(replace.assign = TRUE, width = 60)
options(repos = "http://cran.r-project.org/")

library(knitr)
library(tidyverse)

opts_chunk$set(fig.path = 'figure/', cache.path = 'cache/', tidy = TRUE,
               fig.align = 'center', out.width = '70%', fig.asp = 0.618,
               fig.show = 'hold', fig.pos = 'htpb', par = TRUE, comment = NA)
```
